name       : bsdiff
version    : 1.0.4
release    : 5
source     :
    - https://github.com/clearlinux/bsdiff/archive/v1.0.4.tar.gz : 75d85754374c853e90ebfd132a37fede2103d39d9382e9dc0b0452b96a4526bc
license    : BSD-2-clause
component  : system.utils
summary    : bsdiff and bspatch are tools for building and applying patches to binary files.
description: |
    bsdiff and bspatch are tools for building and applying patches to binary files. By using suffix sorting (specifically, Larsson and Sadakane's qsufsort) and taking advantage of how executable files change, bsdiff routinely produces binary patches 50-80% smaller than those produced by Xdelta, and 15% smaller than those produced by .RTPatch (a commercial patch tool).
    This is a fork by the Clear Linux Project.
builddeps  :
    - pkgconfig(check)
    - bzip2-devel
    - libtool
    - valgrind
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
